### ISSUE TITLE
DatabricksVectorSearch doesn't allow access with service principal client ID/secret

### ISSUE THREAD

**Issue by daisuke834** [databricks/databricks-ai-bridge#33]
[VectorSearchClient](https://api-docs.databricks.com/python/vector-search/databricks.vector_search.html) of `databricks.vector_search.client` can optionally receive the optional arguments `service_principal_client_id=None` and `service_principal_client_secret=None` for allowing access with service principal client ID/secret.

However, [DatabricksVectorSearch](https://github.com/databricks/databricks-ai-bridge/blob/c9946ad183a5a7c18db850da329d6233abcaaa11/integrations/langchain/src/databricks_langchain/vectorstores.py#L41) for langchain integration isn't capable for doing it because it calls `VectorSearchClient()` without any arguments.
```python
        try:
            self.index = VectorSearchClient().get_index(
                endpoint_name=endpoint, index_name=index_name
            )
```
at https://github.com/databricks/databricks-ai-bridge/blob/c9946ad183a5a7c18db850da329d6233abcaaa11/integrations/langchain/src/databricks_langchain/vectorstores.py#L233-L234

Could you fix the code like this?
```python
--- a/vectorstores.py
+++ b/vectorstores.py
@@ -216,6 +216,11 @@ class DatabricksVectorSearch(VectorStore):
         embedding: Optional[Embeddings] = None,
         text_column: Optional[str] = None,
         columns: Optional[List[str]] = None,
+        workspace_url=None,
+        personal_access_token=None,
+        service_principal_client_id=None,
+        service_principal_client_secret=None,
+        disable_notice=False,
     ):
         if not (isinstance(index_name, str) and _INDEX_NAME_PATTERN.match(index_name)):
             raise ValueError(
@@ -234,7 +239,13 @@ class DatabricksVectorSearch(VectorStore):
             ) from e
 
         try:
-            self.index = VectorSearchClient().get_index(
+            self.index = VectorSearchClient(
+                    workspace_url=workspace_url,
+                    personal_access_token=personal_access_token,
+                    service_principal_client_id=service_principal_client_id,
+                    service_principal_client_secret=service_principal_client_secret,
+                    disable_notice=disable_notice
+                ).get_index(
                 endpoint_name=endpoint, index_name=index_name
             )
         except Exception as e:
```

Other alternative solution like https://github.com/databricks/databricks-ai-bridge/pull/27 is also fine with me.

**Comment by chutch1122** [comment]
#27 was just merged!

**Comment by daisuke834** [comment]
@chutch1122 
Thank you!
Closing this issue.
